### ISSUE TITLE
Using an external image will not work properly and will become a small image, such as https://www.google.com/img.jpg

### ISSUE THREAD

**Issue by LeannaClaire** [squeevee/flarum-ext-fancybox#2]
Using an external image will not work properly and will become a small image, such as https://www.google.com/img.jpg

**Comment by LeannaClaire** [comment]
Use the external chain picture, it can not be used normally, it will become a small picture, only the locally uploaded picture can use the enlarged picture normally. When using the external chain picture, the editor will automatically add <a> hyperlink, there is a super chain picture Can't use zoom function normally, attachment view demo, such as https://www.google.com/img.jpg
![微信截图_20190426174618](https://user-images.githubusercontent.com/34939681/56799285-360a6e80-684b-11e9-87cb-341ac0db25ad.png)

![微信图片_20190426174504](https://user-images.githubusercontent.com/34939681/56799231-15421900-684b-11e9-8cd1-addc689b4997.png)

**Comment by LeannaClaire** [comment]
I hope that the images in the outer chain will also start the FancyBox mode, otherwise the experience is too bad, because my pictures are all third-party libraries.

**Comment by squeevee** [comment]
@iosmall 

The way I have designed it, an image wrapped in an external link does this behavior so that the the link will still be available. It looks like the link has the same URL as the image, so it would make sense for this to be an exception to that part of the design.

I'll make this change a part of the next beta release, hopefully within the next week.

I'd like to know more about your situation though, if that's okay.

> my pictures are all third-party libraries

What third-party libraries are you using with regards to the images? Would you mind sharing the markup you used in the post?

**Comment by LeannaClaire** [comment]
Because my pictures are all saved in a third-party gallery.  weibo.com
https://github.com/Semibold/Weibo-Picture-Store

**Comment by LeannaClaire** [comment]
Anyway, as long as it is not a locally uploaded image, it will shrink.

**Comment by LeannaClaire** [comment]
The external chain image I use will automatically add a hyperlink. Very depressed
![微信截图_20190512214203](https://user-images.githubusercontent.com/34939681/57583021-d2489c80-74fe-11e9-9ac5-c41a0450b556.png)

**Comment by LeannaClaire** [comment]
There is a serious problem, the mobile browser can't display the picture.

**Comment by squeevee** [comment]
> Because my pictures are all saved in a third-party gallery. weibo.com
> https://github.com/Semibold/Weibo-Picture-Store

I'm afraid I still don't understand fully. I am not aware of any Weibo extension for Flarum. There is a step in-between uploading the image to Weibo, and putting it on Flarum. Do you copy and paste the URL of the image? Or is there an extension for Flarum that I'm not aware of?

I have issued a new Beta release, so please update your extension, clear your Flarum cache, and see if the issues are still affecting you.

**Comment by squeevee** [comment]
I have not been able to reproduce this issue on version 0.2-beta. using extension fof/formatting I was able to paste the url to an image and it worked as expected. If you're still having issues, please make sure that you have version 0.2-beta installed by running
```sh
composer show squeevee/flarum-ext-fancybox
```
and checking the version number
