### ISSUE TITLE
Support Flarum beta 14

### ISSUE THREAD

**Issue by Kakifrucht** [squeevee/flarum-ext-fancybox#6]
Do you plan on updating this to Flarum beta14?

Thanks

**Comment by Kakifrucht** [comment]
cc @the-turk

**Comment by eddiewebb** [comment]
Pull request #7  does this.

I kept naming convention and printed a tag in my repo `0.2.0-beta.15`  (if you really need back to 14 its just a new tag let me know)

But since I'm not publishing under my own name, until this is ever merged, folks can add github to your `composer.json`

```
    "require": {
        "squeevee/flarum-ext-fancybox": "0.2.0-beta.15",
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/eddiewebb/flarum-ext-fancybox"
        }
    ]
```

**Comment by Kakifrucht** [comment]
closing because fixed and abandoned
